name: Create a comment on new issues

on:
  issues:
    types: [opened]
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "Dump GitHub context"
        run: echo '${{ toJSON(github) }}' | jq
        shell: bash
  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with API
        run: |
          gh api -X POST \
          http://api.github.com/repo/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
          -f body='
          Comment But from api call not action
          '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIXATION: ${{ github.event.organization.log }} 
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        
      
      
    
    
      
